slice_name: Most Popular Rented Film Categories
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 32__table
  viz_type: echarts_timeseries_bar
  slice_id: 76
  x_axis: rental_date
  time_grain_sqla: P1Y
  x_axis_sort_asc: true
  metrics:
  - count
  groupby:
  - category_name
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: rental_date
  timeseries_limit_metric: count
  order_desc: true
  row_limit: 10
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  x_axis_title_margin: 15
  y_axis_title_margin: 30
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetAndPresetColors
  show_legend: true
  legendType: scroll
  legendOrientation: right
  x_axis_time_format: smart_date
  xAxisLabelInterval: auto
  y_axis_format: SMART_NUMBER
  y_axis_bounds:
  - null
  - null
  truncateXAxis: true
  rich_tooltip: true
  showTooltipTotal: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 13
query_context: '{"datasource":{"id":32,"type":"table"},"force":false,"queries":[{"filters":[{"col":"rental_date","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1Y","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1Y","columnType":"BASE_AXIS","sqlExpression":"rental_date","label":"rental_date","expressionType":"SQL"},"category_name"],"metrics":["count"],"orderby":[["count",false]],"annotation_layers":[],"row_limit":10,"series_columns":["category_name"],"series_limit":0,"series_limit_metric":"count","order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["rental_date"],"columns":["category_name"],"aggregates":{"count":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"rename","options":{"columns":{"count":null},"level":0,"inplace":true}},{"operation":"flatten"}]}],"form_data":{"datasource":"32__table","viz_type":"echarts_timeseries_bar","slice_id":76,"x_axis":"rental_date","time_grain_sqla":"P1Y","x_axis_sort_asc":true,"metrics":["count"],"groupby":["category_name"],"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"rental_date"}],"timeseries_limit_metric":"count","order_desc":true,"row_limit":10,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"orientation":"vertical","x_axis_title_margin":15,"y_axis_title_margin":30,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetAndPresetColors","show_legend":true,"legendType":"scroll","legendOrientation":"right","x_axis_time_format":"smart_date","xAxisLabelInterval":"auto","y_axis_format":"SMART_NUMBER","y_axis_bounds":[null,null],"truncateXAxis":true,"rich_tooltip":true,"showTooltipTotal":true,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[13],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: da1fe618-7e57-43cc-8a9a-dce6a7f1ab76
version: 1.0.0
dataset_uuid: d46fb88b-e9b4-4b00-bf22-e94a917eb220
