slice_name: Rental Volume by Country
description: null
certified_by: null
certification_details: null
viz_type: world_map
params:
  datasource: 32__table
  viz_type: world_map
  slice_id: 90
  entity: country_name
  country_fieldtype: name
  metric: count
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: rental_date
  row_limit: 10000
  sort_by_metric: true
  show_bubbles: false
  max_bubble_size: '25'
  color_picker:
    a: 1
    b: 135
    g: 122
    r: 0
  color_by: metric
  linear_color_scheme: superset_seq_1
  y_axis_format: SMART_NUMBER
  extra_form_data: {}
  dashboards:
  - 13
query_context: '{"datasource":{"id":32,"type":"table"},"force":false,"queries":[{"filters":[{"col":"rental_date","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[],"metrics":["count"],"annotation_layers":[],"row_limit":10000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"32__table","viz_type":"world_map","slice_id":90,"entity":"country_name","country_fieldtype":"name","metric":"count","adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"rental_date"}],"row_limit":10000,"sort_by_metric":true,"show_bubbles":false,"max_bubble_size":"25","color_picker":{"a":1,"b":135,"g":122,"r":0},"color_by":"metric","linear_color_scheme":"superset_seq_1","y_axis_format":"SMART_NUMBER","extra_form_data":{},"dashboards":[13],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: af374fe3-d8fc-4e22-bbda-b139cbb7e9b7
version: 1.0.0
dataset_uuid: d46fb88b-e9b4-4b00-bf22-e94a917eb220
