slice_name: Top Average Rental Duration by Country
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 32__table
  viz_type: echarts_timeseries_bar
  slice_id: 79
  x_axis: rental_date
  time_grain_sqla: P1Y
  metrics:
  - avg_rental_duration_days
  groupby:
  - country_name
  adhoc_filters:
  - clause: WHERE
    comparator:
    - 2005
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_mnr1xll56a_ukxt4b620f8
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: rental_date_year_number
  - clause: WHERE
    subject: rental_date
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  row_limit: 10
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  x_axis_title_margin: 15
  y_axis_title_margin: 30
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetAndPresetColors
  show_legend: true
  legendType: scroll
  legendOrientation: right
  x_axis_time_format: smart_date
  xAxisLabelInterval: auto
  y_axis_format: SMART_NUMBER
  y_axis_bounds:
  - null
  - null
  truncateXAxis: true
  rich_tooltip: true
  showTooltipTotal: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 13
query_context: '{"datasource":{"id":32,"type":"table"},"force":false,"queries":[{"filters":[{"col":"rental_date_year_number","op":"IN","val":[2005]},{"col":"rental_date","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1Y","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1Y","columnType":"BASE_AXIS","sqlExpression":"rental_date","label":"rental_date","expressionType":"SQL"},"country_name"],"metrics":["avg_rental_duration_days"],"orderby":[["avg_rental_duration_days",false]],"annotation_layers":[],"row_limit":10,"series_columns":["country_name"],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["rental_date"],"columns":["country_name"],"aggregates":{"avg_rental_duration_days":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"rename","options":{"columns":{"avg_rental_duration_days":null},"level":0,"inplace":true}},{"operation":"flatten"}]}],"form_data":{"datasource":"32__table","viz_type":"echarts_timeseries_bar","slice_id":79,"x_axis":"rental_date","time_grain_sqla":"P1Y","metrics":["avg_rental_duration_days"],"groupby":["country_name"],"adhoc_filters":[{"clause":"WHERE","comparator":[2005],"datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_mnr1xll56a_ukxt4b620f8","isExtra":false,"isNew":false,"operator":"IN","operatorId":"IN","sqlExpression":null,"subject":"rental_date_year_number"},{"clause":"WHERE","subject":"rental_date","operator":"TEMPORAL_RANGE","comparator":"No
  filter","expressionType":"SIMPLE"}],"row_limit":10,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"orientation":"vertical","x_axis_title_margin":15,"y_axis_title_margin":30,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetAndPresetColors","show_legend":true,"legendType":"scroll","legendOrientation":"right","x_axis_time_format":"smart_date","xAxisLabelInterval":"auto","y_axis_format":"SMART_NUMBER","y_axis_bounds":[null,null],"truncateXAxis":true,"rich_tooltip":true,"showTooltipTotal":true,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[13],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 32857121-c301-4cb3-8ec2-a68d631df3e4
version: 1.0.0
dataset_uuid: d46fb88b-e9b4-4b00-bf22-e94a917eb220
