slice_name: Active Devices Activity Breakdown
description: null
certified_by: null
certification_details: null
viz_type: sankey
params:
  datasource: 37__table
  viz_type: sankey
  groupby:
  - device
  - event_type
  metric: count
  adhoc_filters:
  - clause: WHERE
    subject: event_ts
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  row_limit: 10000
  color_scheme: supersetColors
  extra_form_data: {}
  dashboards:
  - 9
query_context: '{"datasource":{"id":37,"type":"table"},"force":false,"queries":[{"filters":[{"col":"event_ts","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["device","event_type"],"metrics":["count"],"annotation_layers":[],"row_limit":10000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"37__table","viz_type":"sankey","groupby":["device","event_type"],"metric":"count","adhoc_filters":[{"clause":"WHERE","subject":"event_ts","operator":"TEMPORAL_RANGE","comparator":"No
  filter","expressionType":"SIMPLE"}],"row_limit":10000,"color_scheme":"supersetColors","extra_form_data":{},"dashboards":[9],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 8430c0a1-b068-4fa9-a270-c6987ee41b76
version: 1.0.0
dataset_uuid: cae40f90-eda2-4c7b-a7b5-d2d3975fb3fd
