slice_name: Clicks per minute
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  datasource: 37__table
  viz_type: echarts_timeseries_line
  x_axis: event_ts
  time_grain_sqla: PT1M
  x_axis_sort_asc: true
  metrics:
  - count
  groupby: []
  adhoc_filters:
  - clause: WHERE
    subject: event_ts
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  x_axis_title_margin: 15
  y_axis_title_margin: 30
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  time_shift_color: true
  seriesType: line
  only_total: true
  opacity: 0.2
  markerSize: 6
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  xAxisLabelInterval: auto
  rich_tooltip: true
  showTooltipTotal: true
  tooltipTimeFormat: smart_date
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  extra_form_data: {}
  dashboards:
  - 9
query_context: '{"datasource":{"id":37,"type":"table"},"force":false,"queries":[{"filters":[{"col":"event_ts","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"PT1M","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"PT1M","columnType":"BASE_AXIS","sqlExpression":"event_ts","label":"event_ts","expressionType":"SQL"}],"metrics":["count"],"orderby":[["count",false]],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["event_ts"],"columns":[],"aggregates":{"count":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"flatten"}]}],"form_data":{"datasource":"37__table","viz_type":"echarts_timeseries_line","x_axis":"event_ts","time_grain_sqla":"PT1M","x_axis_sort_asc":true,"metrics":["count"],"groupby":[],"adhoc_filters":[{"clause":"WHERE","subject":"event_ts","operator":"TEMPORAL_RANGE","comparator":"No
  filter","expressionType":"SIMPLE"}],"order_desc":true,"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"x_axis_title_margin":15,"y_axis_title_margin":30,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","time_shift_color":true,"seriesType":"line","only_total":true,"opacity":0.2,"markerSize":6,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","xAxisLabelInterval":"auto","rich_tooltip":true,"showTooltipTotal":true,"tooltipTimeFormat":"smart_date","y_axis_format":"SMART_NUMBER","truncateXAxis":true,"y_axis_bounds":[null,null],"extra_form_data":{},"dashboards":[9],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 0874136b-b4fe-489c-87c8-d2a6b76f3967
version: 1.0.0
dataset_uuid: cae40f90-eda2-4c7b-a7b5-d2d3975fb3fd
