slice_name: Most Popular Film Categories
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 46__table
  viz_type: echarts_timeseries_bar
  slice_id: 88
  x_axis: window_start
  time_grain_sqla: P1D
  x_axis_sort_asc: true
  metrics:
  - <new metric>
  groupby:
  - category_name
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: window_start
  timeseries_limit_metric: <new metric>
  order_desc: true
  row_limit: 10
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  x_axis_title_margin: 15
  y_axis_title_margin: 30
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetAndPresetColors
  time_shift_color: true
  only_total: true
  show_legend: true
  legendType: scroll
  legendOrientation: right
  x_axis_time_format: '%Y-%m-%d'
  xAxisLabelInterval: auto
  y_axis_format: ~g
  y_axis_bounds:
  - null
  - null
  truncateXAxis: true
  rich_tooltip: true
  showTooltipTotal: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 9
query_context: '{"datasource":{"id":46,"type":"table"},"force":false,"queries":[{"filters":[{"col":"window_start","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","sqlExpression":"window_start","label":"window_start","expressionType":"SQL"},"category_name"],"metrics":["<new
  metric>"],"orderby":[["<new metric>",false]],"annotation_layers":[],"row_limit":10,"series_columns":["category_name"],"series_limit":0,"series_limit_metric":"<new
  metric>","order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["window_start"],"columns":["category_name"],"aggregates":{"<new
  metric>":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"rename","options":{"columns":{"<new
  metric>":null},"level":0,"inplace":true}},{"operation":"flatten"}]}],"form_data":{"datasource":"46__table","viz_type":"echarts_timeseries_bar","slice_id":88,"x_axis":"window_start","time_grain_sqla":"P1D","x_axis_sort_asc":true,"metrics":["<new
  metric>"],"groupby":["category_name"],"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"window_start"}],"timeseries_limit_metric":"<new
  metric>","order_desc":true,"row_limit":10,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"orientation":"vertical","x_axis_title_margin":15,"y_axis_title_margin":30,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetAndPresetColors","time_shift_color":true,"only_total":true,"show_legend":true,"legendType":"scroll","legendOrientation":"right","x_axis_time_format":"%Y-%m-%d","xAxisLabelInterval":"auto","y_axis_format":"~g","y_axis_bounds":[null,null],"truncateXAxis":true,"rich_tooltip":true,"showTooltipTotal":true,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[9],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: fb4f9045-8c8a-447c-9e28-5d50fd2ed29e
version: 1.0.0
dataset_uuid: 0d62a68a-866b-48cc-be29-248c78236800
