slice_name: Most Popular Films
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 46__table
  viz_type: echarts_timeseries_bar
  slice_id: 83
  x_axis: window_start
  time_grain_sqla: P1D
  x_axis_sort_asc: true
  metrics:
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: click_count
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 1035
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: column
      type_generic: 0
      uuid: 98ce7efd-b5f5-4d90-91ad-a8701c4e776b
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: SUM(click_count)
    optionName: metric_uffrq1ne1sf_28scexaasuz
    sqlExpression: null
  groupby:
  - title
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: window_start
  timeseries_limit_metric: count
  order_desc: true
  row_limit: 10
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  x_axis_title_margin: 15
  y_axis_title_margin: 30
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetAndPresetColors
  time_shift_color: true
  only_total: true
  show_legend: true
  legendType: scroll
  legendOrientation: right
  x_axis_time_format: '%Y-%m-%d'
  xAxisLabelInterval: auto
  y_axis_format: SMART_NUMBER
  y_axis_bounds:
  - null
  - null
  truncateXAxis: true
  rich_tooltip: true
  showTooltipTotal: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 9
query_context: '{"datasource":{"id":46,"type":"table"},"force":false,"queries":[{"filters":[{"col":"window_start","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","sqlExpression":"window_start","label":"window_start","expressionType":"SQL"},"title"],"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"click_count","description":null,"expression":null,"filterable":true,"groupby":true,"id":1035,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"column","type_generic":0,"uuid":"98ce7efd-b5f5-4d90-91ad-a8701c4e776b","verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(click_count)","optionName":"metric_uffrq1ne1sf_28scexaasuz","sqlExpression":null}],"orderby":[["count",false]],"annotation_layers":[],"row_limit":10,"series_columns":["title"],"series_limit":0,"series_limit_metric":"count","order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["window_start"],"columns":["title"],"aggregates":{"SUM(click_count)":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"rename","options":{"columns":{"SUM(click_count)":null},"level":0,"inplace":true}},{"operation":"flatten"}]}],"form_data":{"datasource":"46__table","viz_type":"echarts_timeseries_bar","slice_id":83,"x_axis":"window_start","time_grain_sqla":"P1D","x_axis_sort_asc":true,"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"click_count","description":null,"expression":null,"filterable":true,"groupby":true,"id":1035,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"column","type_generic":0,"uuid":"98ce7efd-b5f5-4d90-91ad-a8701c4e776b","verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(click_count)","optionName":"metric_uffrq1ne1sf_28scexaasuz","sqlExpression":null}],"groupby":["title"],"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"window_start"}],"timeseries_limit_metric":"count","order_desc":true,"row_limit":10,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"orientation":"vertical","x_axis_title_margin":15,"y_axis_title_margin":30,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetAndPresetColors","time_shift_color":true,"only_total":true,"show_legend":true,"legendType":"scroll","legendOrientation":"right","x_axis_time_format":"%Y-%m-%d","xAxisLabelInterval":"auto","y_axis_format":"SMART_NUMBER","y_axis_bounds":[null,null],"truncateXAxis":true,"rich_tooltip":true,"showTooltipTotal":true,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[9],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: b6c83dc7-322a-4204-b9ce-ed14fe92ed30
version: 1.0.0
dataset_uuid: 0d62a68a-866b-48cc-be29-248c78236800
