slice_name: User Activity by Device
description: null
certified_by: null
certification_details: null
viz_type: pie
params:
  datasource: 37__table
  viz_type: pie
  groupby:
  - device
  metric: count
  adhoc_filters:
  - clause: WHERE
    subject: event_ts
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  row_limit: 1000
  sort_by_metric: false
  color_scheme: supersetColors
  show_labels_threshold: 5
  show_legend: true
  legendType: scroll
  legendOrientation: top
  label_type: key
  number_format: SMART_NUMBER
  date_format: smart_date
  show_labels: true
  labels_outside: true
  outerRadius: 70
  innerRadius: 30
  extra_form_data: {}
  dashboards:
  - 9
query_context: '{"datasource":{"id":37,"type":"table"},"force":false,"queries":[{"filters":[{"col":"event_ts","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["device"],"metrics":["count"],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"37__table","viz_type":"pie","groupby":["device"],"metric":"count","adhoc_filters":[{"clause":"WHERE","subject":"event_ts","operator":"TEMPORAL_RANGE","comparator":"No
  filter","expressionType":"SIMPLE"}],"row_limit":1000,"sort_by_metric":false,"color_scheme":"supersetColors","show_labels_threshold":5,"show_legend":true,"legendType":"scroll","legendOrientation":"top","label_type":"key","number_format":"SMART_NUMBER","date_format":"smart_date","show_labels":true,"labels_outside":true,"outerRadius":70,"innerRadius":30,"extra_form_data":{},"dashboards":[9],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: acd8297f-d7c2-488c-812a-84a3dffff6be
version: 1.0.0
dataset_uuid: cae40f90-eda2-4c7b-a7b5-d2d3975fb3fd
